root = "."
tmp_dir = ".runtime/air"

[build]
  cmd = "go build -o .runtime/air/onlydemo ."
  entrypoint = [".runtime/air/onlydemo", "serve"]
  delay = 1000
  exclude_dir = [".git", ".runtime", "frontend", "node_modules", "dist"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "sql", "html"]
  kill_delay = "500ms"
  log = ".runtime/air/build-errors.log"
  send_interrupt = true

[log]
  time = true

[misc]
  clean_on_exit = true
