import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'
import { useState } from 'react'
import { request } from '../api'
import type { Channel, Post } from '../models'
import { Badge, Button, EmptyState, ErrorState, Icon, Loading, date, money } from '../components/ui'
import { PostCard } from '../components/cards'
import { useAuth } from '../auth'
interface AccountData { user?: { id: string; username: string; email?: string }; manageable_channels?: Channel[]; purchased_posts?: Post[]; subscriptions?: Array<{ id: string; status: string; channel_name?: string; amount_cents?: number; currency?: string; current_period_end?: string }> }
export function AccountPage() { const [search] = useSearchParams(); const [tab, setTab] = useState(search.get('tab') || 'library'); const data = useQuery({ queryKey: ['me-dashboard'], queryFn: () => request<AccountData>('/api/v1/me') }); const cancel = useMutation({ mutationFn: (id: string) => request(`/billing/v1/me/subscriptions/${id}/cancel`, { method: 'POST', body: JSON.stringify({}) }), onSuccess: () => void data.refetch() }); const auth = useAuth(); if (data.isPending) return <Loading />; if (data.error) return <ErrorState error={data.error} retry={() => void data.refetch()} />; const value = data.data || {}; return <><div className="page-heading"><span className="eyebrow">Your reading space</span><h1>{auth.user?.username || 'My library'}</h1><p>Purchased stories stay yours. Channel membership and editorial access are managed separately.</p></div><div className="tabs" role="tablist">{[['library','Purchased posts'],['subscriptions','Memberships'],['channels','My channels'],['billing','Billing history']].map(([key,label]) => <button key={key} className={`tab ${tab === key ? 'active' : ''}`} onClick={() => setTab(key)} role="tab" aria-selected={tab === key}>{label}</button>)}</div>{tab === 'library' && <Library posts={value.purchased_posts || []} />}{tab === 'subscriptions' && <Subscriptions subscriptions={value.subscriptions || []} cancel={cancel} />}{tab === 'channels' && <Channels channels={value.manageable_channels || []} />}{tab === 'billing' && <Billing />}</> }
function Library({ posts }: { posts: Post[] }) { return posts.length ? <div className="card-grid">{posts.map((post) => <PostCard post={{ ...post, purchased: true, can_read: true }} key={post.id} />)}</div> : <EmptyState icon="book" title="Your shelf is waiting." action={<Link to="/" className="button button-primary">Explore stories</Link>}>When you buy a post, it will stay here permanently.</EmptyState> }
function Subscriptions({ subscriptions, cancel }: { subscriptions: AccountData['subscriptions']; cancel: { isPending: boolean; mutate: (id: string) => void } }) { return subscriptions?.length ? <div className="panel"><div className="panel-heading"><div><h2>Channel memberships</h2><p>Membership access follows the active subscription period.</p></div></div><div className="data-list">{subscriptions.map((subscription) => <div className="data-row" key={subscription.id}><span className="avatar"><Icon name="users" size={16} /></span><div className="data-row-main"><h3>{subscription.channel_name || 'Channel membership'}</h3><p>Renews or ends {date(subscription.current_period_end)}</p></div><Badge tone={subscription.status === 'active' ? 'success' : 'warning'}>{subscription.status}</Badge>{subscription.amount_cents && <span className="amount">{money(subscription.amount_cents, subscription.currency)}</span>}<div className="data-row-actions">{subscription.status === 'active' && <Button variant="secondary" busy={cancel.isPending} onClick={() => cancel.mutate(subscription.id)}>Cancel</Button>}</div></div>)}</div></div> : <EmptyState icon="users" title="No active memberships." action={<Link to="/channels" className="button button-secondary">Browse channels</Link>}>Join a channel when you want its current and future membership posts.</EmptyState> }
function Channels({ channels }: { channels: Channel[] }) { return channels.length ? <div className="channel-grid">{channels.map((channel) => <article className="channel-card" key={channel.id}><div className="channel-avatar">{channel.name.slice(0, 1)}</div><div><h3>{channel.name}</h3><p>@{channel.slug}</p></div><div className="channel-card-footer"><Badge tone="brand">{channel.role}</Badge><Link className="text-button" to={`/channels/${channel.id}`}>Manage <Icon name="arrow" size={13} /></Link></div></article>)}</div> : <EmptyState icon="settings" title="No channels to manage." action={<Link className="button button-primary" to="/channels">Explore channels</Link>}>When you create a channel, owner and editor tools will appear here.</EmptyState> }
function Billing() { return <EmptyState icon="wallet" title="Billing history is coming into view." >Confirmed purchases and invoices will appear here once the billing summary endpoint is enabled.</EmptyState> }
