import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { request } from '../api'
import { useAuth } from '../auth'
import type { Channel, Post } from '../models'
import { Badge, Button, EmptyState, ErrorState, Field, Icon, Loading, Modal } from '../components/ui'
import { PostCard } from '../components/cards'
import { useState, type FormEvent } from 'react'

export function ChannelPage() {
  const { id = '' } = useParams(); const client = useQueryClient(); const [manage, setManage] = useState(false)
  const channel = useQuery({ queryKey: ['channel', id], queryFn: () => request<Channel>(`/api/v1/channels/${id}`, {}, false) })
  const posts = useQuery({ queryKey: ['channel-posts', id], queryFn: () => request<Post[]>(`/api/v1/posts?channel_id=${encodeURIComponent(id)}`, {}, false), enabled: !!id })
  const createPost = useMutation({ mutationFn: (body: { channel_id: string; title: string; slug: string; body: string; access_policy: string; price_cents?: number }) => request<Post>('/api/v1/posts', { method: 'POST', body: JSON.stringify(body) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['channel-posts', id] }); setManage(false) } })
  if (channel.isPending) return <Loading />
  if (channel.error || !channel.data) return <ErrorState error={channel.error || new Error('Channel not found.')} />
  const current = channel.data
  return <><div className="channel-banner"><div className="channel-banner-row"><div><span className="eyebrow">Channel</span><h1>{current.name}</h1><p>@{current.slug}{current.description ? ` · ${current.description}` : ''}</p></div><div className="channel-banner-actions">{current.subscription_active ? <Badge tone="success"><Icon name="check" size={12} />Member</Badge> : current.offers?.some((offer) => offer.mode === 'subscription' && offer.active) && <Button variant="secondary">Join channel</Button>}{current.can_manage && <Button onClick={() => setManage(true)}><Icon name="plus" size={16} />New post</Button>}</div></div></div><div className="tabs"><button className="tab active">Posts</button><button className="tab">About</button>{current.can_manage && <button className="tab" onClick={() => setManage(true)}><Icon name="settings" size={15} />Manage</button>}</div>{posts.isPending ? <Loading cards /> : posts.error ? <ErrorState error={posts.error} retry={() => void posts.refetch()} /> : posts.data?.length ? <div className="card-grid">{posts.data.map((post) => <PostCard post={post} key={post.id} />)}</div> : <EmptyState icon="book" title="No posts yet." action={current.can_manage ? <Button onClick={() => setManage(true)}>Write the first post</Button> : undefined}>Check back soon for the first story from this channel.</EmptyState>}{current.can_manage && <PostEditor open={manage} onClose={() => setManage(false)} busy={createPost.isPending} error={createPost.error} onSubmit={(input) => createPost.mutate({ ...input, channel_id: id })} />}</>
}
function PostEditor({ open, onClose, busy, error, onSubmit }: { open: boolean; onClose: () => void; busy: boolean; error: Error | null; onSubmit: (input: { title: string; slug: string; body: string; access_policy: string; price_cents?: number }) => void }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const policy = String(data.get('access_policy')); onSubmit({ title: String(data.get('title')).trim(), slug: String(data.get('slug')).trim(), body: String(data.get('body')), access_policy: policy, price_cents: policy === 'ppv' || policy === 'members_ppv' ? Math.round(Number(data.get('price')) * 100) : undefined }) }
  return <Modal open={open} onOpenChange={(value) => { if (!value) onClose() }} title="Write a new post" description="All posts belong to this channel. You can change the access policy before publishing." wide><form className="stack" onSubmit={submit}><div className="input-row"><Field label="Title"><input name="title" required maxLength={200} autoFocus /></Field><Field label="Slug"><input name="slug" required pattern="[a-z0-9-]+" placeholder="a-short-slug" /></Field></div><Field label="Story"><textarea name="body" className="editor-body" required placeholder="Start writing…" /></Field><fieldset className="stack" style={{ border: 0, padding: 0, margin: 0 }}><legend className="field">Access policy</legend><div className="choice-grid"><label className="choice"><input type="radio" name="access_policy" value="public" defaultChecked /><span><strong>Free to read</strong><small>Anyone can open it.</small></span></label><label className="choice"><input type="radio" name="access_policy" value="membership" /><span><strong>Membership</strong><small>Included for current and future members.</small></span></label><label className="choice"><input type="radio" name="access_policy" value="members_ppv" /><span><strong>Member purchase</strong><small>Membership is required to buy; access stays permanent.</small></span></label><label className="choice"><input type="radio" name="access_policy" value="ppv" /><span><strong>Open purchase</strong><small>Anyone can buy; access stays permanent.</small></span></label></div></fieldset><Field label="One-time price (USD)" hint="Only used for a purchase policy. The backend remains the source of offer and currency truth."><input name="price" type="number" min="0.5" step="0.01" placeholder="9.00" /></Field>{error && <p className="form-error" role="alert">{error.message}</p>}<div className="form-actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" busy={busy}>Publish post<Icon name="arrow" size={16} /></Button></div></form></Modal>
}

export function NewChannelPage() {
  const auth = useAuth(); const navigate = useNavigate(); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  if (!auth.user) return <EmptyState icon="users" title="Sign in to start a channel." action={<Button onClick={auth.openLogin}>Sign in</Button>} />
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{const channel=await request<Channel>('/api/v1/channels',{method:'POST',body:JSON.stringify({slug:String(d.get('slug')).trim(),name:String(d.get('name')).trim(),description:String(d.get('description')||'').trim()})});navigate(`/channels/${channel.id}`)}catch(cause){setError(cause instanceof Error?cause.message:'Channel could not be created.')}finally{setBusy(false)}}
  return <div className="page-narrow"><div className="page-heading"><span className="eyebrow">Start publishing</span><h1>Create a channel</h1><p>Your channel is the home for your archive. You become its owner and can invite editors after it exists.</p></div><div className="panel"><form className="stack" onSubmit={submit}><Field label="Channel name"><input name="name" required maxLength={120} autoFocus placeholder="A name readers will remember" /></Field><Field label="Slug" hint="Lowercase letters, numbers, and dashes. This becomes the channel’s stable address."><input name="slug" required pattern="[a-z0-9-]+" placeholder="my-channel" /></Field><Field label="Description"><textarea name="description" maxLength={500} placeholder="What will readers find here?" /></Field>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Link className="button button-ghost" to="/channels">Cancel</Link><Button type="submit" busy={busy}>Create channel<Icon name="arrow" size={16}/></Button></div></form></div></div>
}
