import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useState } from 'react'
import { request } from '../api'
import { useAuth } from '../auth'
import type { Checkout, Post } from '../models'
import { Badge, Button, EmptyState, ErrorState, Icon, Loading, Modal, date, money } from '../components/ui'
import { policyLabels, policyOf } from '../models'

export function PostPage() {
  const { id = '' } = useParams(); const auth = useAuth(); const navigate = useNavigate(); const post = useQuery({ queryKey: ['post', id], queryFn: () => request<Post>(`/api/v1/posts/${id}`, {}, false) }); const [purchaseOpen, setPurchaseOpen] = useState(false)
  const checkout = useMutation({ mutationFn: () => request<{ url?: string; id: string }>(`/api/v1/posts/${id}/checkout`, { method: 'POST', headers: { 'Idempotency-Key': `post-${id}-${auth.user?.id || 'guest'}` }, body: JSON.stringify({ return_url: `${location.origin}/checkout/return` }) }), onSuccess: (result) => { if (result.url) location.assign(result.url); else navigate(`/checkout/return?checkout_id=${encodeURIComponent(result.id)}`) } })
  if (post.isPending) return <Loading />
  if (post.error || !post.data) return <ErrorState error={post.error || new Error('Post not found.')} />
  const item = post.data; const policy = policyOf(item); const price = item.offers?.flatMap((offer) => offer.prices).find((candidate) => candidate.active && !offerSubscription(item, candidate.id)) || (item.price_cents ? { amount_cents: item.price_cents, currency: item.currency || 'USD' } : undefined); const locked = !item.can_read && !item.purchased
  return <><div className="breadcrumb"><Link to="/">Explore</Link><Icon name="chevron" size={13} /><Link to={`/channels/${item.channel_id}`}>{item.channel_name || 'Channel'}</Link><Icon name="chevron" size={13} /><span>{item.title}</span></div><div className="reader-layout"><article className="reader-main"><span className="eyebrow">{item.channel_name || 'Independent channel'}</span><h1 className="reader-title">{item.title}</h1><div className="reader-meta"><span className="avatar">{(item.channel_name || 'O').slice(0, 1)}</span><span>{item.channel_name || 'OpenRails creator'}</span><span>·</span><span>{date(item.created_at)}</span>{item.purchased && <Badge tone="success"><Icon name="check" size={11} />In your library</Badge>}</div>{locked ? <div className="locked-content"><div className="empty-icon"><Icon name="lock" size={27} /></div><h2>This story is waiting for you.</h2><p>{policy === 'membership' ? 'Join this channel to read this post and future membership stories.' : policy === 'members_ppv' ? 'Channel membership is required to purchase this post. Your purchase remains yours after membership ends.' : 'Buy this post once and keep access permanently.'}</p>{!auth.user ? <Button onClick={auth.openLogin}>Sign in to continue</Button> : policy === 'membership' ? <Button>Join channel</Button> : <Button onClick={() => setPurchaseOpen(true)}>{price ? `Buy for ${money(price.amount_cents, price.currency)}` : 'View purchase options'}</Button>}</div> : <div className="article-body">{item.body || <EmptyState title="This post has no body yet." />}</div>}</article><aside className="panel purchase-panel"><Badge tone={item.purchased ? 'success' : policy === 'public' ? 'neutral' : 'brand'}>{item.purchased ? 'Permanent access' : policyLabels[policy]}</Badge><h3>{item.purchased ? 'Keep reading.' : policy === 'public' ? 'Open reading.' : 'Access this story.'}</h3><p>{item.purchased ? 'This purchase remains in your library even if your membership changes.' : policy === 'public' ? 'No account is required to read this post.' : 'The channel decides how readers access this work; you will review the terms before any payment.'}</p>{!item.can_read && item.price_cents != null && <><div className="purchase-price">{money(item.price_cents, item.currency)} <small>one time</small></div><Button className="button-full" onClick={() => auth.user ? setPurchaseOpen(true) : auth.openLogin()}>{auth.user ? 'Buy this post' : 'Sign in to buy'}</Button></>}{item.can_read && policy !== 'public' && <Badge tone="success"><Icon name="check" size={11} />You have access</Badge>}<div className="purchase-note"><Icon name="lock" size={14} /><span>Payments open in the configured Stripe test checkout. We only show success after the server confirms your checkout.</span></div></aside></div><PurchaseDialog open={purchaseOpen} onClose={() => setPurchaseOpen(false)} busy={checkout.isPending} error={checkout.error} post={item} onConfirm={() => checkout.mutate()} /></>
}
function offerSubscription(post: Post, priceID: string) { return post.offers?.some((offer) => offer.mode === 'subscription' && offer.prices.some((price) => price.id === priceID)) }
function PurchaseDialog({ open, onClose, busy, error, post, onConfirm }: { open: boolean; onClose: () => void; busy: boolean; error: Error | null; post: Post; onConfirm: () => void }) { const price = post.price_cents ? money(post.price_cents, post.currency) : 'the listed price'; return <Modal open={open} onOpenChange={(value) => { if (!value) onClose() }} title="Review your purchase" description="This is a one-time purchase. You keep access permanently, even if your channel membership later ends."><div className="stack"><div className="notice"><Icon name="check" /><p><strong>{post.title}</strong><br />{price} · Permanent access</p></div>{error && <p className="form-error" role="alert">{error.message}</p>}<div className="form-actions"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button busy={busy} onClick={onConfirm}>Continue to secure checkout<Icon name="external" size={15} /></Button></div></div></Modal> }
export function CheckoutReturnPage() { const [search] = useSearchParams(); const id = search.get('checkout_id') || ''; const status = useQuery({ queryKey: ['checkout', id], queryFn: () => request<Checkout>(`/api/v1/checkouts/${encodeURIComponent(id)}`), enabled: !!id, refetchInterval: (query) => query.state.data?.status === 'succeeded' ? false : 1500 }); if (!id) return <EmptyState icon="warning" title="Checkout reference missing." />; if (status.isPending) return <Loading />; if (status.error) return <ErrorState error={status.error} retry={() => void status.refetch()} />; const value = status.data!; if (value.status !== 'succeeded') return <div className="centered-page"><span className="eyebrow">Payment pending</span><h1 style={{ marginTop: 16 }}>We’re confirming your access.</h1><p>Keep this page open while the payment provider confirms your checkout. We never grant access from the redirect alone.</p><div className="inline-actions"><span className="spinner" />{value.status === 'failed' ? 'Payment failed.' : 'Checking securely…'}</div></div>; return <div className="centered-page"><div className="empty-icon" style={{ color: 'var(--success)' }}><Icon name="check" size={30} /></div><span className="eyebrow">Purchase confirmed</span><h1 style={{ marginTop: 16 }}>It’s yours to keep.</h1><p>The server confirmed your payment and added this story to your library.</p><div className="inline-actions"><Link to="/me?tab=library" className="button button-primary">Open my library<Icon name="arrow" size={16} /></Link><Link to="/" className="button button-secondary">Keep exploring</Link></div></div> }
